### ISSUE TITLE
Question while build the sampler

### ISSUE THREAD

**Issue by zcoo** [SiyuanQi/human-centric-scene-synthesis#5]
https://github.com/SiyuanQi/human-centric-scene-synthesis/blob/6f2215d07052426f0f4a27b8ca71844ea5d347c4/src/cpp/main.cpp#L37
There we need to modify the paths.
I wonder how is the "suncgRoot " path organized or structured?
Is that just like "suncgRoot/house"  "suncgRoot/room"  "suncgRoot/object"  or other?

**Comment by SiyuanQi-zz** [comment]
Hi, it is supposed to be "suncgRoot/suncg_data/house", "suncgRoot/suncg_data/room", etc.
`suncg_data` is the folder extracted from the dataset downloaded.

**Comment by zcoo** [comment]
oh, thanks a lot for help!
Although I have successfully running that by reading some codes, still thank you for answering!
